# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Hardware
  #version: 1.0
  folders:

          #  - title:
          #    output: pdf
    #    type: frontmatter
    #    folderitems:
            #    - title:
            #      url: /titlepage.html
      #      output: pdf
      #      type: frontmatter
      #    - title:
            #      url: /tocpage.html
      #      output: pdf
      #      type: frontmatter

  - title: Overview
    output: web
    folderitems:
    - title: CCTV market
      url: /p1_landing_page.html
      output: web
    - title: New board
      url: /board_new.html
      output: web 

  - title: By vendor
    output: web
    folderitems:
    - title: XM
      url: /p1_sample1.html
      output: web

    - title: JVT
      url: /p1_sample2.html
      output: web

    - title: Ruision
      url: /p1_sample3.html
      output: web

  - title: By SoC
    output: web

    folderitems:
    - title: hi3516av100
      url: /p1_sample4.html
      output: web

    - title: hi3516av200
      url: /p1_sample5.html
      output: web

    - title: hi3516cv100
      url: /p1_sample6.html
      output: web

    - title: hi3516cv200
      url: /p1_sample7.html
      output: web

    - title: hi3516cv300
      url: /p1_sample7.html
      output: web

    - title: hi3516cv500
      url: /p1_sample7.html
      output: web

    - title: hi3516ev200
      url: /p1_sample7.html
      output: web

    - title: hi3519av100
      url: /p1_sample7.html
      output: web

    - title: hi3536dv100
      url: /p1_sample7.html
      output: web




